### PR TITLE
discordv2.0 compatibility update. 

### PR DESCRIPTION
**Pull request by therealOri**
Updated:

- Using app/slash commands now.
- Using asyncio instead of "time".
- Using toml config for stuff instead of manually writing everything into multiple spots.
- Fixed some issues with restarting the MC server. It was messing up many chunks and was causing errors and also causing broken PIPEs because it wasn't waiting long enough before continuing to restart.
- Removed redundant/repeated comments.

### CODE REVIEW

**Comment by therealOri** [comment]
You may ignore the README.md file in this request. (You can even have everything here be in a separate folder) . But yeah, basically just making it work with discord's slash commands and client stuff. (also fixing some issues I ran into when running the minecraft server and java on linux.

**Comment by therealOri** [comment]
Note!

NOTHING of what I made has been tested on windows yet. So idk if the commands and stuff will still work. (Please make sure to test before anything)

**Comment by kitOSx** [comment]
imma be honest im new to programming (most ive had was 4 years in compsci in highschool) but this looks cool, plus i used ! instead of / because using /ban would also ban someone in discord

**Comment by therealOri** [comment]
> imma be honest im new to programming (most ive had was 4 years in compsci in highschool) but this looks cool, plus i used ! instead of / because using /ban would also ban someone in discord

Thanks! You also did a great job on the code to be honest.

And the name of the commands can always be changed "/ban" could be "/mc_ban" instead if it causes issues. But other than that, I don't use a windows operating system so feel free to do some testing and messing around with the code to see what works and what breaks. (let me know what breaks so I know what to work on)

**Pull request merged**
